"""db changes

Revision ID: 0c1916ca0a04
Revises: 1c6daee24838
Create Date: 2025-07-16 22:50:46.279231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1916ca0a04'
down_revision = '1c6daee24838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resID', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'results', ['resID'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('resID')

    # ### end Alembic commands ###
