"""db undo changes

Revision ID: f50d50145f38
Revises: 0c1916ca0a04
Create Date: 2025-07-16 22:52:40.842966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f50d50145f38'
down_revision = '0c1916ca0a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('profiles_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('resID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resID', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('profiles_ibfk_2'), 'results', ['resID'], ['id'])

    # ### end Alembic commands ###
